/*
HookSniff API

Testing RateLimitsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hooksniff

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_hooksniff_RateLimitsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RateLimitsAPIService RateLimitsEndpointIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var endpointId string

		httpRes, err := apiClient.RateLimitsAPI.RateLimitsEndpointIdDelete(context.Background(), endpointId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RateLimitsAPIService RateLimitsEndpointIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var endpointId string

		httpRes, err := apiClient.RateLimitsAPI.RateLimitsEndpointIdGet(context.Background(), endpointId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RateLimitsAPIService RateLimitsEndpointIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var endpointId string

		httpRes, err := apiClient.RateLimitsAPI.RateLimitsEndpointIdPost(context.Background(), endpointId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RateLimitsAPIService RateLimitsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.RateLimitsAPI.RateLimitsGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
