/*
HookSniff API

Testing InboundAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hooksniff

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_hooksniff_InboundAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InboundAPIService InboundProviderEndpointIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string
		var endpointId string

		httpRes, err := apiClient.InboundAPI.InboundProviderEndpointIdPost(context.Background(), provider, endpointId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InboundAPIService InboundProviderPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		httpRes, err := apiClient.InboundAPI.InboundProviderPost(context.Background(), provider).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
