/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTransformRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransformRuleRequest{}

// CreateTransformRuleRequest struct for CreateTransformRuleRequest
type CreateTransformRuleRequest struct {
	Name string `json:"name"`
	RuleType string `json:"rule_type"`
	Config map[string]interface{} `json:"config"`
}

type _CreateTransformRuleRequest CreateTransformRuleRequest

// NewCreateTransformRuleRequest instantiates a new CreateTransformRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransformRuleRequest(name string, ruleType string, config map[string]interface{}) *CreateTransformRuleRequest {
	this := CreateTransformRuleRequest{}
	this.Name = name
	this.RuleType = ruleType
	this.Config = config
	return &this
}

// NewCreateTransformRuleRequestWithDefaults instantiates a new CreateTransformRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransformRuleRequestWithDefaults() *CreateTransformRuleRequest {
	this := CreateTransformRuleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTransformRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTransformRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTransformRuleRequest) SetName(v string) {
	o.Name = v
}

// GetRuleType returns the RuleType field value
func (o *CreateTransformRuleRequest) GetRuleType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RuleType
}

// GetRuleTypeOk returns a tuple with the RuleType field value
// and a boolean to check if the value has been set.
func (o *CreateTransformRuleRequest) GetRuleTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleType, true
}

// SetRuleType sets field value
func (o *CreateTransformRuleRequest) SetRuleType(v string) {
	o.RuleType = v
}

// GetConfig returns the Config field value
func (o *CreateTransformRuleRequest) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *CreateTransformRuleRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *CreateTransformRuleRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o CreateTransformRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTransformRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["rule_type"] = o.RuleType
	toSerialize["config"] = o.Config
	return toSerialize, nil
}

func (o *CreateTransformRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"rule_type",
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTransformRuleRequest := _CreateTransformRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTransformRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateTransformRuleRequest(varCreateTransformRuleRequest)

	return err
}

type NullableCreateTransformRuleRequest struct {
	value *CreateTransformRuleRequest
	isSet bool
}

func (v NullableCreateTransformRuleRequest) Get() *CreateTransformRuleRequest {
	return v.value
}

func (v *NullableCreateTransformRuleRequest) Set(val *CreateTransformRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTransformRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTransformRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTransformRuleRequest(val *CreateTransformRuleRequest) *NullableCreateTransformRuleRequest {
	return &NullableCreateTransformRuleRequest{value: val, isSet: true}
}

func (v NullableCreateTransformRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTransformRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


