/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the NotificationsUnreadCountGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationsUnreadCountGet200Response{}

// NotificationsUnreadCountGet200Response struct for NotificationsUnreadCountGet200Response
type NotificationsUnreadCountGet200Response struct {
	Count *int32 `json:"count,omitempty"`
}

// NewNotificationsUnreadCountGet200Response instantiates a new NotificationsUnreadCountGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationsUnreadCountGet200Response() *NotificationsUnreadCountGet200Response {
	this := NotificationsUnreadCountGet200Response{}
	return &this
}

// NewNotificationsUnreadCountGet200ResponseWithDefaults instantiates a new NotificationsUnreadCountGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationsUnreadCountGet200ResponseWithDefaults() *NotificationsUnreadCountGet200Response {
	this := NotificationsUnreadCountGet200Response{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *NotificationsUnreadCountGet200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsUnreadCountGet200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *NotificationsUnreadCountGet200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *NotificationsUnreadCountGet200Response) SetCount(v int32) {
	o.Count = &v
}

func (o NotificationsUnreadCountGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationsUnreadCountGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableNotificationsUnreadCountGet200Response struct {
	value *NotificationsUnreadCountGet200Response
	isSet bool
}

func (v NullableNotificationsUnreadCountGet200Response) Get() *NotificationsUnreadCountGet200Response {
	return v.value
}

func (v *NullableNotificationsUnreadCountGet200Response) Set(val *NotificationsUnreadCountGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationsUnreadCountGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationsUnreadCountGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationsUnreadCountGet200Response(val *NotificationsUnreadCountGet200Response) *NullableNotificationsUnreadCountGet200Response {
	return &NullableNotificationsUnreadCountGet200Response{value: val, isSet: true}
}

func (v NullableNotificationsUnreadCountGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationsUnreadCountGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


