/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResendVerificationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResendVerificationRequest{}

// ResendVerificationRequest struct for ResendVerificationRequest
type ResendVerificationRequest struct {
	Email string `json:"email"`
}

type _ResendVerificationRequest ResendVerificationRequest

// NewResendVerificationRequest instantiates a new ResendVerificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResendVerificationRequest(email string) *ResendVerificationRequest {
	this := ResendVerificationRequest{}
	this.Email = email
	return &this
}

// NewResendVerificationRequestWithDefaults instantiates a new ResendVerificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResendVerificationRequestWithDefaults() *ResendVerificationRequest {
	this := ResendVerificationRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *ResendVerificationRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ResendVerificationRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ResendVerificationRequest) SetEmail(v string) {
	o.Email = v
}

func (o ResendVerificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResendVerificationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *ResendVerificationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResendVerificationRequest := _ResendVerificationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResendVerificationRequest)

	if err != nil {
		return err
	}

	*o = ResendVerificationRequest(varResendVerificationRequest)

	return err
}

type NullableResendVerificationRequest struct {
	value *ResendVerificationRequest
	isSet bool
}

func (v NullableResendVerificationRequest) Get() *ResendVerificationRequest {
	return v.value
}

func (v *NullableResendVerificationRequest) Set(val *ResendVerificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResendVerificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResendVerificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResendVerificationRequest(val *ResendVerificationRequest) *NullableResendVerificationRequest {
	return &NullableResendVerificationRequest{value: val, isSet: true}
}

func (v NullableResendVerificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResendVerificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


