/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
)

// checks if the Delivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delivery{}

// Delivery struct for Delivery
type Delivery struct {
	Id *string `json:"id,omitempty"`
	EndpointId *string `json:"endpoint_id,omitempty"`
	Event NullableString `json:"event,omitempty"`
	Status *string `json:"status,omitempty"`
	AttemptCount *int32 `json:"attempt_count,omitempty"`
	ResponseStatus NullableInt32 `json:"response_status,omitempty"`
	ReplayCount *int32 `json:"replay_count,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewDelivery instantiates a new Delivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelivery() *Delivery {
	this := Delivery{}
	return &this
}

// NewDeliveryWithDefaults instantiates a new Delivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryWithDefaults() *Delivery {
	this := Delivery{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Delivery) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Delivery) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Delivery) SetId(v string) {
	o.Id = &v
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *Delivery) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *Delivery) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *Delivery) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetEvent returns the Event field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Delivery) GetEvent() string {
	if o == nil || IsNil(o.Event.Get()) {
		var ret string
		return ret
	}
	return *o.Event.Get()
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Delivery) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Event.Get(), o.Event.IsSet()
}

// HasEvent returns a boolean if a field has been set.
func (o *Delivery) HasEvent() bool {
	if o != nil && o.Event.IsSet() {
		return true
	}

	return false
}

// SetEvent gets a reference to the given NullableString and assigns it to the Event field.
func (o *Delivery) SetEvent(v string) {
	o.Event.Set(&v)
}
// SetEventNil sets the value for Event to be an explicit nil
func (o *Delivery) SetEventNil() {
	o.Event.Set(nil)
}

// UnsetEvent ensures that no value is present for Event, not even an explicit nil
func (o *Delivery) UnsetEvent() {
	o.Event.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Delivery) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Delivery) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Delivery) SetStatus(v string) {
	o.Status = &v
}

// GetAttemptCount returns the AttemptCount field value if set, zero value otherwise.
func (o *Delivery) GetAttemptCount() int32 {
	if o == nil || IsNil(o.AttemptCount) {
		var ret int32
		return ret
	}
	return *o.AttemptCount
}

// GetAttemptCountOk returns a tuple with the AttemptCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetAttemptCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AttemptCount) {
		return nil, false
	}
	return o.AttemptCount, true
}

// HasAttemptCount returns a boolean if a field has been set.
func (o *Delivery) HasAttemptCount() bool {
	if o != nil && !IsNil(o.AttemptCount) {
		return true
	}

	return false
}

// SetAttemptCount gets a reference to the given int32 and assigns it to the AttemptCount field.
func (o *Delivery) SetAttemptCount(v int32) {
	o.AttemptCount = &v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Delivery) GetResponseStatus() int32 {
	if o == nil || IsNil(o.ResponseStatus.Get()) {
		var ret int32
		return ret
	}
	return *o.ResponseStatus.Get()
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Delivery) GetResponseStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResponseStatus.Get(), o.ResponseStatus.IsSet()
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *Delivery) HasResponseStatus() bool {
	if o != nil && o.ResponseStatus.IsSet() {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given NullableInt32 and assigns it to the ResponseStatus field.
func (o *Delivery) SetResponseStatus(v int32) {
	o.ResponseStatus.Set(&v)
}
// SetResponseStatusNil sets the value for ResponseStatus to be an explicit nil
func (o *Delivery) SetResponseStatusNil() {
	o.ResponseStatus.Set(nil)
}

// UnsetResponseStatus ensures that no value is present for ResponseStatus, not even an explicit nil
func (o *Delivery) UnsetResponseStatus() {
	o.ResponseStatus.Unset()
}

// GetReplayCount returns the ReplayCount field value if set, zero value otherwise.
func (o *Delivery) GetReplayCount() int32 {
	if o == nil || IsNil(o.ReplayCount) {
		var ret int32
		return ret
	}
	return *o.ReplayCount
}

// GetReplayCountOk returns a tuple with the ReplayCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetReplayCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ReplayCount) {
		return nil, false
	}
	return o.ReplayCount, true
}

// HasReplayCount returns a boolean if a field has been set.
func (o *Delivery) HasReplayCount() bool {
	if o != nil && !IsNil(o.ReplayCount) {
		return true
	}

	return false
}

// SetReplayCount gets a reference to the given int32 and assigns it to the ReplayCount field.
func (o *Delivery) SetReplayCount(v int32) {
	o.ReplayCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Delivery) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Delivery) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Delivery) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o Delivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.EndpointId) {
		toSerialize["endpoint_id"] = o.EndpointId
	}
	if o.Event.IsSet() {
		toSerialize["event"] = o.Event.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.AttemptCount) {
		toSerialize["attempt_count"] = o.AttemptCount
	}
	if o.ResponseStatus.IsSet() {
		toSerialize["response_status"] = o.ResponseStatus.Get()
	}
	if !IsNil(o.ReplayCount) {
		toSerialize["replay_count"] = o.ReplayCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableDelivery struct {
	value *Delivery
	isSet bool
}

func (v NullableDelivery) Get() *Delivery {
	return v.value
}

func (v *NullableDelivery) Set(val *Delivery) {
	v.value = val
	v.isSet = true
}

func (v NullableDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelivery(val *Delivery) *NullableDelivery {
	return &NullableDelivery{value: val, isSet: true}
}

func (v NullableDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


