/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the SystemStatsPlanBreakdownInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatsPlanBreakdownInner{}

// SystemStatsPlanBreakdownInner struct for SystemStatsPlanBreakdownInner
type SystemStatsPlanBreakdownInner struct {
	Plan *string `json:"plan,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewSystemStatsPlanBreakdownInner instantiates a new SystemStatsPlanBreakdownInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatsPlanBreakdownInner() *SystemStatsPlanBreakdownInner {
	this := SystemStatsPlanBreakdownInner{}
	return &this
}

// NewSystemStatsPlanBreakdownInnerWithDefaults instantiates a new SystemStatsPlanBreakdownInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatsPlanBreakdownInnerWithDefaults() *SystemStatsPlanBreakdownInner {
	this := SystemStatsPlanBreakdownInner{}
	return &this
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *SystemStatsPlanBreakdownInner) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatsPlanBreakdownInner) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *SystemStatsPlanBreakdownInner) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *SystemStatsPlanBreakdownInner) SetPlan(v string) {
	o.Plan = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SystemStatsPlanBreakdownInner) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatsPlanBreakdownInner) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SystemStatsPlanBreakdownInner) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SystemStatsPlanBreakdownInner) SetCount(v int32) {
	o.Count = &v
}

func (o SystemStatsPlanBreakdownInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatsPlanBreakdownInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableSystemStatsPlanBreakdownInner struct {
	value *SystemStatsPlanBreakdownInner
	isSet bool
}

func (v NullableSystemStatsPlanBreakdownInner) Get() *SystemStatsPlanBreakdownInner {
	return v.value
}

func (v *NullableSystemStatsPlanBreakdownInner) Set(val *SystemStatsPlanBreakdownInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatsPlanBreakdownInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatsPlanBreakdownInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatsPlanBreakdownInner(val *SystemStatsPlanBreakdownInner) *NullableSystemStatsPlanBreakdownInner {
	return &NullableSystemStatsPlanBreakdownInner{value: val, isSet: true}
}

func (v NullableSystemStatsPlanBreakdownInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatsPlanBreakdownInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


