/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the UpgradeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeResponse{}

// UpgradeResponse struct for UpgradeResponse
type UpgradeResponse struct {
	CheckoutUrl NullableString `json:"checkout_url,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUpgradeResponse instantiates a new UpgradeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeResponse() *UpgradeResponse {
	this := UpgradeResponse{}
	return &this
}

// NewUpgradeResponseWithDefaults instantiates a new UpgradeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeResponseWithDefaults() *UpgradeResponse {
	this := UpgradeResponse{}
	return &this
}

// GetCheckoutUrl returns the CheckoutUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpgradeResponse) GetCheckoutUrl() string {
	if o == nil || IsNil(o.CheckoutUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CheckoutUrl.Get()
}

// GetCheckoutUrlOk returns a tuple with the CheckoutUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpgradeResponse) GetCheckoutUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CheckoutUrl.Get(), o.CheckoutUrl.IsSet()
}

// HasCheckoutUrl returns a boolean if a field has been set.
func (o *UpgradeResponse) HasCheckoutUrl() bool {
	if o != nil && o.CheckoutUrl.IsSet() {
		return true
	}

	return false
}

// SetCheckoutUrl gets a reference to the given NullableString and assigns it to the CheckoutUrl field.
func (o *UpgradeResponse) SetCheckoutUrl(v string) {
	o.CheckoutUrl.Set(&v)
}
// SetCheckoutUrlNil sets the value for CheckoutUrl to be an explicit nil
func (o *UpgradeResponse) SetCheckoutUrlNil() {
	o.CheckoutUrl.Set(nil)
}

// UnsetCheckoutUrl ensures that no value is present for CheckoutUrl, not even an explicit nil
func (o *UpgradeResponse) UnsetCheckoutUrl() {
	o.CheckoutUrl.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *UpgradeResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeResponse) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *UpgradeResponse) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *UpgradeResponse) SetProvider(v string) {
	o.Provider = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpgradeResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpgradeResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpgradeResponse) SetMessage(v string) {
	o.Message = &v
}

func (o UpgradeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CheckoutUrl.IsSet() {
		toSerialize["checkout_url"] = o.CheckoutUrl.Get()
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUpgradeResponse struct {
	value *UpgradeResponse
	isSet bool
}

func (v NullableUpgradeResponse) Get() *UpgradeResponse {
	return v.value
}

func (v *NullableUpgradeResponse) Set(val *UpgradeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeResponse(val *UpgradeResponse) *NullableUpgradeResponse {
	return &NullableUpgradeResponse{value: val, isSet: true}
}

func (v NullableUpgradeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


