/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the CreateApiKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApiKeyResponse{}

// CreateApiKeyResponse struct for CreateApiKeyResponse
type CreateApiKeyResponse struct {
	Id *string `json:"id,omitempty"`
	// Full API key — only shown once
	Key *string `json:"key,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCreateApiKeyResponse instantiates a new CreateApiKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApiKeyResponse() *CreateApiKeyResponse {
	this := CreateApiKeyResponse{}
	return &this
}

// NewCreateApiKeyResponseWithDefaults instantiates a new CreateApiKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApiKeyResponseWithDefaults() *CreateApiKeyResponse {
	this := CreateApiKeyResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateApiKeyResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiKeyResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateApiKeyResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateApiKeyResponse) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CreateApiKeyResponse) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiKeyResponse) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CreateApiKeyResponse) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CreateApiKeyResponse) SetKey(v string) {
	o.Key = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *CreateApiKeyResponse) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiKeyResponse) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *CreateApiKeyResponse) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *CreateApiKeyResponse) SetPrefix(v string) {
	o.Prefix = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateApiKeyResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiKeyResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateApiKeyResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateApiKeyResponse) SetMessage(v string) {
	o.Message = &v
}

func (o CreateApiKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApiKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateApiKeyResponse struct {
	value *CreateApiKeyResponse
	isSet bool
}

func (v NullableCreateApiKeyResponse) Get() *CreateApiKeyResponse {
	return v.value
}

func (v *NullableCreateApiKeyResponse) Set(val *CreateApiKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApiKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApiKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApiKeyResponse(val *CreateApiKeyResponse) *NullableCreateApiKeyResponse {
	return &NullableCreateApiKeyResponse{value: val, isSet: true}
}

func (v NullableCreateApiKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApiKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


