/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the PaginatedUsers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedUsers{}

// PaginatedUsers struct for PaginatedUsers
type PaginatedUsers struct {
	Users []UserSummary `json:"users,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Page *int32 `json:"page,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
}

// NewPaginatedUsers instantiates a new PaginatedUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedUsers() *PaginatedUsers {
	this := PaginatedUsers{}
	return &this
}

// NewPaginatedUsersWithDefaults instantiates a new PaginatedUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedUsersWithDefaults() *PaginatedUsers {
	this := PaginatedUsers{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *PaginatedUsers) GetUsers() []UserSummary {
	if o == nil || IsNil(o.Users) {
		var ret []UserSummary
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedUsers) GetUsersOk() ([]UserSummary, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *PaginatedUsers) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []UserSummary and assigns it to the Users field.
func (o *PaginatedUsers) SetUsers(v []UserSummary) {
	o.Users = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PaginatedUsers) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedUsers) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PaginatedUsers) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *PaginatedUsers) SetTotal(v int32) {
	o.Total = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PaginatedUsers) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedUsers) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PaginatedUsers) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *PaginatedUsers) SetPage(v int32) {
	o.Page = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *PaginatedUsers) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedUsers) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *PaginatedUsers) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *PaginatedUsers) SetPerPage(v int32) {
	o.PerPage = &v
}

func (o PaginatedUsers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedUsers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	return toSerialize, nil
}

type NullablePaginatedUsers struct {
	value *PaginatedUsers
	isSet bool
}

func (v NullablePaginatedUsers) Get() *PaginatedUsers {
	return v.value
}

func (v *NullablePaginatedUsers) Set(val *PaginatedUsers) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedUsers) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedUsers(val *PaginatedUsers) *NullablePaginatedUsers {
	return &NullablePaginatedUsers{value: val, isSet: true}
}

func (v NullablePaginatedUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


