/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangeRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeRoleRequest{}

// ChangeRoleRequest struct for ChangeRoleRequest
type ChangeRoleRequest struct {
	Role string `json:"role"`
}

type _ChangeRoleRequest ChangeRoleRequest

// NewChangeRoleRequest instantiates a new ChangeRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeRoleRequest(role string) *ChangeRoleRequest {
	this := ChangeRoleRequest{}
	this.Role = role
	return &this
}

// NewChangeRoleRequestWithDefaults instantiates a new ChangeRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeRoleRequestWithDefaults() *ChangeRoleRequest {
	this := ChangeRoleRequest{}
	return &this
}

// GetRole returns the Role field value
func (o *ChangeRoleRequest) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ChangeRoleRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ChangeRoleRequest) SetRole(v string) {
	o.Role = v
}

func (o ChangeRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *ChangeRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeRoleRequest := _ChangeRoleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeRoleRequest)

	if err != nil {
		return err
	}

	*o = ChangeRoleRequest(varChangeRoleRequest)

	return err
}

type NullableChangeRoleRequest struct {
	value *ChangeRoleRequest
	isSet bool
}

func (v NullableChangeRoleRequest) Get() *ChangeRoleRequest {
	return v.value
}

func (v *NullableChangeRoleRequest) Set(val *ChangeRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeRoleRequest(val *ChangeRoleRequest) *NullableChangeRoleRequest {
	return &NullableChangeRoleRequest{value: val, isSet: true}
}

func (v NullableChangeRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


