/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplyTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyTemplateRequest{}

// ApplyTemplateRequest struct for ApplyTemplateRequest
type ApplyTemplateRequest struct {
	EndpointId string `json:"endpoint_id"`
	Variables map[string]interface{} `json:"variables,omitempty"`
}

type _ApplyTemplateRequest ApplyTemplateRequest

// NewApplyTemplateRequest instantiates a new ApplyTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyTemplateRequest(endpointId string) *ApplyTemplateRequest {
	this := ApplyTemplateRequest{}
	this.EndpointId = endpointId
	return &this
}

// NewApplyTemplateRequestWithDefaults instantiates a new ApplyTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyTemplateRequestWithDefaults() *ApplyTemplateRequest {
	this := ApplyTemplateRequest{}
	return &this
}

// GetEndpointId returns the EndpointId field value
func (o *ApplyTemplateRequest) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *ApplyTemplateRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *ApplyTemplateRequest) SetEndpointId(v string) {
	o.EndpointId = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *ApplyTemplateRequest) GetVariables() map[string]interface{} {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]interface{}
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTemplateRequest) GetVariablesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]interface{}{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *ApplyTemplateRequest) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]interface{} and assigns it to the Variables field.
func (o *ApplyTemplateRequest) SetVariables(v map[string]interface{}) {
	o.Variables = v
}

func (o ApplyTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint_id"] = o.EndpointId
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

func (o *ApplyTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyTemplateRequest := _ApplyTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyTemplateRequest)

	if err != nil {
		return err
	}

	*o = ApplyTemplateRequest(varApplyTemplateRequest)

	return err
}

type NullableApplyTemplateRequest struct {
	value *ApplyTemplateRequest
	isSet bool
}

func (v NullableApplyTemplateRequest) Get() *ApplyTemplateRequest {
	return v.value
}

func (v *NullableApplyTemplateRequest) Set(val *ApplyTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyTemplateRequest(val *ApplyTemplateRequest) *NullableApplyTemplateRequest {
	return &NullableApplyTemplateRequest{value: val, isSet: true}
}

func (v NullableApplyTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


