/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the AdminSdkUpdatePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminSdkUpdatePostRequest{}

// AdminSdkUpdatePostRequest struct for AdminSdkUpdatePostRequest
type AdminSdkUpdatePostRequest struct {
	Version *string `json:"version,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewAdminSdkUpdatePostRequest instantiates a new AdminSdkUpdatePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminSdkUpdatePostRequest() *AdminSdkUpdatePostRequest {
	this := AdminSdkUpdatePostRequest{}
	return &this
}

// NewAdminSdkUpdatePostRequestWithDefaults instantiates a new AdminSdkUpdatePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminSdkUpdatePostRequestWithDefaults() *AdminSdkUpdatePostRequest {
	this := AdminSdkUpdatePostRequest{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AdminSdkUpdatePostRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminSdkUpdatePostRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AdminSdkUpdatePostRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *AdminSdkUpdatePostRequest) SetVersion(v string) {
	o.Version = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AdminSdkUpdatePostRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminSdkUpdatePostRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AdminSdkUpdatePostRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AdminSdkUpdatePostRequest) SetMessage(v string) {
	o.Message = &v
}

func (o AdminSdkUpdatePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminSdkUpdatePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableAdminSdkUpdatePostRequest struct {
	value *AdminSdkUpdatePostRequest
	isSet bool
}

func (v NullableAdminSdkUpdatePostRequest) Get() *AdminSdkUpdatePostRequest {
	return v.value
}

func (v *NullableAdminSdkUpdatePostRequest) Set(val *AdminSdkUpdatePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminSdkUpdatePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminSdkUpdatePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminSdkUpdatePostRequest(val *AdminSdkUpdatePostRequest) *NullableAdminSdkUpdatePostRequest {
	return &NullableAdminSdkUpdatePostRequest{value: val, isSet: true}
}

func (v NullableAdminSdkUpdatePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminSdkUpdatePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


