/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidateEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateEventRequest{}

// ValidateEventRequest struct for ValidateEventRequest
type ValidateEventRequest struct {
	Event map[string]interface{} `json:"event"`
}

type _ValidateEventRequest ValidateEventRequest

// NewValidateEventRequest instantiates a new ValidateEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateEventRequest(event map[string]interface{}) *ValidateEventRequest {
	this := ValidateEventRequest{}
	this.Event = event
	return &this
}

// NewValidateEventRequestWithDefaults instantiates a new ValidateEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateEventRequestWithDefaults() *ValidateEventRequest {
	this := ValidateEventRequest{}
	return &this
}

// GetEvent returns the Event field value
func (o *ValidateEventRequest) GetEvent() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *ValidateEventRequest) GetEventOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Event, true
}

// SetEvent sets field value
func (o *ValidateEventRequest) SetEvent(v map[string]interface{}) {
	o.Event = v
}

func (o ValidateEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	return toSerialize, nil
}

func (o *ValidateEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateEventRequest := _ValidateEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateEventRequest)

	if err != nil {
		return err
	}

	*o = ValidateEventRequest(varValidateEventRequest)

	return err
}

type NullableValidateEventRequest struct {
	value *ValidateEventRequest
	isSet bool
}

func (v NullableValidateEventRequest) Get() *ValidateEventRequest {
	return v.value
}

func (v *NullableValidateEventRequest) Set(val *ValidateEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateEventRequest(val *ValidateEventRequest) *NullableValidateEventRequest {
	return &NullableValidateEventRequest{value: val, isSet: true}
}

func (v NullableValidateEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


