/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the SystemStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatus{}

// SystemStatus struct for SystemStatus
type SystemStatus struct {
	OverallStatus *string `json:"overall_status,omitempty"`
	Uptime30d *float32 `json:"uptime_30d,omitempty"`
	Components []SystemStatusComponentsInner `json:"components,omitempty"`
	CheckedAt *string `json:"checked_at,omitempty"`
}

// NewSystemStatus instantiates a new SystemStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatus() *SystemStatus {
	this := SystemStatus{}
	return &this
}

// NewSystemStatusWithDefaults instantiates a new SystemStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatusWithDefaults() *SystemStatus {
	this := SystemStatus{}
	return &this
}

// GetOverallStatus returns the OverallStatus field value if set, zero value otherwise.
func (o *SystemStatus) GetOverallStatus() string {
	if o == nil || IsNil(o.OverallStatus) {
		var ret string
		return ret
	}
	return *o.OverallStatus
}

// GetOverallStatusOk returns a tuple with the OverallStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetOverallStatusOk() (*string, bool) {
	if o == nil || IsNil(o.OverallStatus) {
		return nil, false
	}
	return o.OverallStatus, true
}

// HasOverallStatus returns a boolean if a field has been set.
func (o *SystemStatus) HasOverallStatus() bool {
	if o != nil && !IsNil(o.OverallStatus) {
		return true
	}

	return false
}

// SetOverallStatus gets a reference to the given string and assigns it to the OverallStatus field.
func (o *SystemStatus) SetOverallStatus(v string) {
	o.OverallStatus = &v
}

// GetUptime30d returns the Uptime30d field value if set, zero value otherwise.
func (o *SystemStatus) GetUptime30d() float32 {
	if o == nil || IsNil(o.Uptime30d) {
		var ret float32
		return ret
	}
	return *o.Uptime30d
}

// GetUptime30dOk returns a tuple with the Uptime30d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetUptime30dOk() (*float32, bool) {
	if o == nil || IsNil(o.Uptime30d) {
		return nil, false
	}
	return o.Uptime30d, true
}

// HasUptime30d returns a boolean if a field has been set.
func (o *SystemStatus) HasUptime30d() bool {
	if o != nil && !IsNil(o.Uptime30d) {
		return true
	}

	return false
}

// SetUptime30d gets a reference to the given float32 and assigns it to the Uptime30d field.
func (o *SystemStatus) SetUptime30d(v float32) {
	o.Uptime30d = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *SystemStatus) GetComponents() []SystemStatusComponentsInner {
	if o == nil || IsNil(o.Components) {
		var ret []SystemStatusComponentsInner
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetComponentsOk() ([]SystemStatusComponentsInner, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *SystemStatus) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []SystemStatusComponentsInner and assigns it to the Components field.
func (o *SystemStatus) SetComponents(v []SystemStatusComponentsInner) {
	o.Components = v
}

// GetCheckedAt returns the CheckedAt field value if set, zero value otherwise.
func (o *SystemStatus) GetCheckedAt() string {
	if o == nil || IsNil(o.CheckedAt) {
		var ret string
		return ret
	}
	return *o.CheckedAt
}

// GetCheckedAtOk returns a tuple with the CheckedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetCheckedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CheckedAt) {
		return nil, false
	}
	return o.CheckedAt, true
}

// HasCheckedAt returns a boolean if a field has been set.
func (o *SystemStatus) HasCheckedAt() bool {
	if o != nil && !IsNil(o.CheckedAt) {
		return true
	}

	return false
}

// SetCheckedAt gets a reference to the given string and assigns it to the CheckedAt field.
func (o *SystemStatus) SetCheckedAt(v string) {
	o.CheckedAt = &v
}

func (o SystemStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OverallStatus) {
		toSerialize["overall_status"] = o.OverallStatus
	}
	if !IsNil(o.Uptime30d) {
		toSerialize["uptime_30d"] = o.Uptime30d
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	if !IsNil(o.CheckedAt) {
		toSerialize["checked_at"] = o.CheckedAt
	}
	return toSerialize, nil
}

type NullableSystemStatus struct {
	value *SystemStatus
	isSet bool
}

func (v NullableSystemStatus) Get() *SystemStatus {
	return v.value
}

func (v *NullableSystemStatus) Set(val *SystemStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatus(val *SystemStatus) *NullableSystemStatus {
	return &NullableSystemStatus{value: val, isSet: true}
}

func (v NullableSystemStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


