/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the StreamParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamParams{}

// StreamParams struct for StreamParams
type StreamParams struct {
	EndpointId *string `json:"endpoint_id,omitempty"`
	Status *string `json:"status,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

// NewStreamParams instantiates a new StreamParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamParams() *StreamParams {
	this := StreamParams{}
	var limit int32 = 50
	this.Limit = &limit
	return &this
}

// NewStreamParamsWithDefaults instantiates a new StreamParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamParamsWithDefaults() *StreamParams {
	this := StreamParams{}
	var limit int32 = 50
	this.Limit = &limit
	return &this
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *StreamParams) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamParams) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *StreamParams) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *StreamParams) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StreamParams) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamParams) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StreamParams) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *StreamParams) SetStatus(v string) {
	o.Status = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *StreamParams) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamParams) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *StreamParams) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *StreamParams) SetLimit(v int32) {
	o.Limit = &v
}

func (o StreamParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointId) {
		toSerialize["endpoint_id"] = o.EndpointId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullableStreamParams struct {
	value *StreamParams
	isSet bool
}

func (v NullableStreamParams) Get() *StreamParams {
	return v.value
}

func (v *NullableStreamParams) Set(val *StreamParams) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamParams) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamParams(val *StreamParams) *NullableStreamParams {
	return &NullableStreamParams{value: val, isSet: true}
}

func (v NullableStreamParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


