/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
)

// checks if the DeviceTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceTokenResponse{}

// DeviceTokenResponse struct for DeviceTokenResponse
type DeviceTokenResponse struct {
	Id *string `json:"id,omitempty"`
	Token *string `json:"token,omitempty"`
	Platform *string `json:"platform,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewDeviceTokenResponse instantiates a new DeviceTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceTokenResponse() *DeviceTokenResponse {
	this := DeviceTokenResponse{}
	return &this
}

// NewDeviceTokenResponseWithDefaults instantiates a new DeviceTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceTokenResponseWithDefaults() *DeviceTokenResponse {
	this := DeviceTokenResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeviceTokenResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceTokenResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeviceTokenResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeviceTokenResponse) SetId(v string) {
	o.Id = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *DeviceTokenResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *DeviceTokenResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *DeviceTokenResponse) SetToken(v string) {
	o.Token = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *DeviceTokenResponse) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceTokenResponse) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *DeviceTokenResponse) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *DeviceTokenResponse) SetPlatform(v string) {
	o.Platform = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DeviceTokenResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceTokenResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DeviceTokenResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DeviceTokenResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o DeviceTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableDeviceTokenResponse struct {
	value *DeviceTokenResponse
	isSet bool
}

func (v NullableDeviceTokenResponse) Get() *DeviceTokenResponse {
	return v.value
}

func (v *NullableDeviceTokenResponse) Set(val *DeviceTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceTokenResponse(val *DeviceTokenResponse) *NullableDeviceTokenResponse {
	return &NullableDeviceTokenResponse{value: val, isSet: true}
}

func (v NullableDeviceTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


