/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the LatencyTrendResponseBucketsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LatencyTrendResponseBucketsInner{}

// LatencyTrendResponseBucketsInner struct for LatencyTrendResponseBucketsInner
type LatencyTrendResponseBucketsInner struct {
	Timestamp *string `json:"timestamp,omitempty"`
	AvgMs *float32 `json:"avg_ms,omitempty"`
	P95Ms *float32 `json:"p95_ms,omitempty"`
}

// NewLatencyTrendResponseBucketsInner instantiates a new LatencyTrendResponseBucketsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLatencyTrendResponseBucketsInner() *LatencyTrendResponseBucketsInner {
	this := LatencyTrendResponseBucketsInner{}
	return &this
}

// NewLatencyTrendResponseBucketsInnerWithDefaults instantiates a new LatencyTrendResponseBucketsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLatencyTrendResponseBucketsInnerWithDefaults() *LatencyTrendResponseBucketsInner {
	this := LatencyTrendResponseBucketsInner{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *LatencyTrendResponseBucketsInner) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LatencyTrendResponseBucketsInner) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *LatencyTrendResponseBucketsInner) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *LatencyTrendResponseBucketsInner) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetAvgMs returns the AvgMs field value if set, zero value otherwise.
func (o *LatencyTrendResponseBucketsInner) GetAvgMs() float32 {
	if o == nil || IsNil(o.AvgMs) {
		var ret float32
		return ret
	}
	return *o.AvgMs
}

// GetAvgMsOk returns a tuple with the AvgMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LatencyTrendResponseBucketsInner) GetAvgMsOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgMs) {
		return nil, false
	}
	return o.AvgMs, true
}

// HasAvgMs returns a boolean if a field has been set.
func (o *LatencyTrendResponseBucketsInner) HasAvgMs() bool {
	if o != nil && !IsNil(o.AvgMs) {
		return true
	}

	return false
}

// SetAvgMs gets a reference to the given float32 and assigns it to the AvgMs field.
func (o *LatencyTrendResponseBucketsInner) SetAvgMs(v float32) {
	o.AvgMs = &v
}

// GetP95Ms returns the P95Ms field value if set, zero value otherwise.
func (o *LatencyTrendResponseBucketsInner) GetP95Ms() float32 {
	if o == nil || IsNil(o.P95Ms) {
		var ret float32
		return ret
	}
	return *o.P95Ms
}

// GetP95MsOk returns a tuple with the P95Ms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LatencyTrendResponseBucketsInner) GetP95MsOk() (*float32, bool) {
	if o == nil || IsNil(o.P95Ms) {
		return nil, false
	}
	return o.P95Ms, true
}

// HasP95Ms returns a boolean if a field has been set.
func (o *LatencyTrendResponseBucketsInner) HasP95Ms() bool {
	if o != nil && !IsNil(o.P95Ms) {
		return true
	}

	return false
}

// SetP95Ms gets a reference to the given float32 and assigns it to the P95Ms field.
func (o *LatencyTrendResponseBucketsInner) SetP95Ms(v float32) {
	o.P95Ms = &v
}

func (o LatencyTrendResponseBucketsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LatencyTrendResponseBucketsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.AvgMs) {
		toSerialize["avg_ms"] = o.AvgMs
	}
	if !IsNil(o.P95Ms) {
		toSerialize["p95_ms"] = o.P95Ms
	}
	return toSerialize, nil
}

type NullableLatencyTrendResponseBucketsInner struct {
	value *LatencyTrendResponseBucketsInner
	isSet bool
}

func (v NullableLatencyTrendResponseBucketsInner) Get() *LatencyTrendResponseBucketsInner {
	return v.value
}

func (v *NullableLatencyTrendResponseBucketsInner) Set(val *LatencyTrendResponseBucketsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLatencyTrendResponseBucketsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLatencyTrendResponseBucketsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLatencyTrendResponseBucketsInner(val *LatencyTrendResponseBucketsInner) *NullableLatencyTrendResponseBucketsInner {
	return &NullableLatencyTrendResponseBucketsInner{value: val, isSet: true}
}

func (v NullableLatencyTrendResponseBucketsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLatencyTrendResponseBucketsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


