/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the RetryPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetryPolicy{}

// RetryPolicy struct for RetryPolicy
type RetryPolicy struct {
	MaxAttempts *int32 `json:"max_attempts,omitempty"`
	Backoff *string `json:"backoff,omitempty"`
	InitialDelaySecs *int32 `json:"initial_delay_secs,omitempty"`
	MaxDelaySecs *int32 `json:"max_delay_secs,omitempty"`
}

// NewRetryPolicy instantiates a new RetryPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetryPolicy() *RetryPolicy {
	this := RetryPolicy{}
	var maxAttempts int32 = 3
	this.MaxAttempts = &maxAttempts
	var backoff string = "exponential"
	this.Backoff = &backoff
	var initialDelaySecs int32 = 10
	this.InitialDelaySecs = &initialDelaySecs
	var maxDelaySecs int32 = 3600
	this.MaxDelaySecs = &maxDelaySecs
	return &this
}

// NewRetryPolicyWithDefaults instantiates a new RetryPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetryPolicyWithDefaults() *RetryPolicy {
	this := RetryPolicy{}
	var maxAttempts int32 = 3
	this.MaxAttempts = &maxAttempts
	var backoff string = "exponential"
	this.Backoff = &backoff
	var initialDelaySecs int32 = 10
	this.InitialDelaySecs = &initialDelaySecs
	var maxDelaySecs int32 = 3600
	this.MaxDelaySecs = &maxDelaySecs
	return &this
}

// GetMaxAttempts returns the MaxAttempts field value if set, zero value otherwise.
func (o *RetryPolicy) GetMaxAttempts() int32 {
	if o == nil || IsNil(o.MaxAttempts) {
		var ret int32
		return ret
	}
	return *o.MaxAttempts
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxAttempts) {
		return nil, false
	}
	return o.MaxAttempts, true
}

// HasMaxAttempts returns a boolean if a field has been set.
func (o *RetryPolicy) HasMaxAttempts() bool {
	if o != nil && !IsNil(o.MaxAttempts) {
		return true
	}

	return false
}

// SetMaxAttempts gets a reference to the given int32 and assigns it to the MaxAttempts field.
func (o *RetryPolicy) SetMaxAttempts(v int32) {
	o.MaxAttempts = &v
}

// GetBackoff returns the Backoff field value if set, zero value otherwise.
func (o *RetryPolicy) GetBackoff() string {
	if o == nil || IsNil(o.Backoff) {
		var ret string
		return ret
	}
	return *o.Backoff
}

// GetBackoffOk returns a tuple with the Backoff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetBackoffOk() (*string, bool) {
	if o == nil || IsNil(o.Backoff) {
		return nil, false
	}
	return o.Backoff, true
}

// HasBackoff returns a boolean if a field has been set.
func (o *RetryPolicy) HasBackoff() bool {
	if o != nil && !IsNil(o.Backoff) {
		return true
	}

	return false
}

// SetBackoff gets a reference to the given string and assigns it to the Backoff field.
func (o *RetryPolicy) SetBackoff(v string) {
	o.Backoff = &v
}

// GetInitialDelaySecs returns the InitialDelaySecs field value if set, zero value otherwise.
func (o *RetryPolicy) GetInitialDelaySecs() int32 {
	if o == nil || IsNil(o.InitialDelaySecs) {
		var ret int32
		return ret
	}
	return *o.InitialDelaySecs
}

// GetInitialDelaySecsOk returns a tuple with the InitialDelaySecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetInitialDelaySecsOk() (*int32, bool) {
	if o == nil || IsNil(o.InitialDelaySecs) {
		return nil, false
	}
	return o.InitialDelaySecs, true
}

// HasInitialDelaySecs returns a boolean if a field has been set.
func (o *RetryPolicy) HasInitialDelaySecs() bool {
	if o != nil && !IsNil(o.InitialDelaySecs) {
		return true
	}

	return false
}

// SetInitialDelaySecs gets a reference to the given int32 and assigns it to the InitialDelaySecs field.
func (o *RetryPolicy) SetInitialDelaySecs(v int32) {
	o.InitialDelaySecs = &v
}

// GetMaxDelaySecs returns the MaxDelaySecs field value if set, zero value otherwise.
func (o *RetryPolicy) GetMaxDelaySecs() int32 {
	if o == nil || IsNil(o.MaxDelaySecs) {
		var ret int32
		return ret
	}
	return *o.MaxDelaySecs
}

// GetMaxDelaySecsOk returns a tuple with the MaxDelaySecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetryPolicy) GetMaxDelaySecsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDelaySecs) {
		return nil, false
	}
	return o.MaxDelaySecs, true
}

// HasMaxDelaySecs returns a boolean if a field has been set.
func (o *RetryPolicy) HasMaxDelaySecs() bool {
	if o != nil && !IsNil(o.MaxDelaySecs) {
		return true
	}

	return false
}

// SetMaxDelaySecs gets a reference to the given int32 and assigns it to the MaxDelaySecs field.
func (o *RetryPolicy) SetMaxDelaySecs(v int32) {
	o.MaxDelaySecs = &v
}

func (o RetryPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetryPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxAttempts) {
		toSerialize["max_attempts"] = o.MaxAttempts
	}
	if !IsNil(o.Backoff) {
		toSerialize["backoff"] = o.Backoff
	}
	if !IsNil(o.InitialDelaySecs) {
		toSerialize["initial_delay_secs"] = o.InitialDelaySecs
	}
	if !IsNil(o.MaxDelaySecs) {
		toSerialize["max_delay_secs"] = o.MaxDelaySecs
	}
	return toSerialize, nil
}

type NullableRetryPolicy struct {
	value *RetryPolicy
	isSet bool
}

func (v NullableRetryPolicy) Get() *RetryPolicy {
	return v.value
}

func (v *NullableRetryPolicy) Set(val *RetryPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableRetryPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableRetryPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetryPolicy(val *RetryPolicy) *NullableRetryPolicy {
	return &NullableRetryPolicy{value: val, isSet: true}
}

func (v NullableRetryPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetryPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


