/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the OutboundIpsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutboundIpsResponse{}

// OutboundIpsResponse struct for OutboundIpsResponse
type OutboundIpsResponse struct {
	Ips []string `json:"ips,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewOutboundIpsResponse instantiates a new OutboundIpsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutboundIpsResponse() *OutboundIpsResponse {
	this := OutboundIpsResponse{}
	return &this
}

// NewOutboundIpsResponseWithDefaults instantiates a new OutboundIpsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutboundIpsResponseWithDefaults() *OutboundIpsResponse {
	this := OutboundIpsResponse{}
	return &this
}

// GetIps returns the Ips field value if set, zero value otherwise.
func (o *OutboundIpsResponse) GetIps() []string {
	if o == nil || IsNil(o.Ips) {
		var ret []string
		return ret
	}
	return o.Ips
}

// GetIpsOk returns a tuple with the Ips field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutboundIpsResponse) GetIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ips) {
		return nil, false
	}
	return o.Ips, true
}

// HasIps returns a boolean if a field has been set.
func (o *OutboundIpsResponse) HasIps() bool {
	if o != nil && !IsNil(o.Ips) {
		return true
	}

	return false
}

// SetIps gets a reference to the given []string and assigns it to the Ips field.
func (o *OutboundIpsResponse) SetIps(v []string) {
	o.Ips = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *OutboundIpsResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutboundIpsResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *OutboundIpsResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *OutboundIpsResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o OutboundIpsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutboundIpsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ips) {
		toSerialize["ips"] = o.Ips
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableOutboundIpsResponse struct {
	value *OutboundIpsResponse
	isSet bool
}

func (v NullableOutboundIpsResponse) Get() *OutboundIpsResponse {
	return v.value
}

func (v *NullableOutboundIpsResponse) Set(val *OutboundIpsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOutboundIpsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOutboundIpsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutboundIpsResponse(val *OutboundIpsResponse) *NullableOutboundIpsResponse {
	return &NullableOutboundIpsResponse{value: val, isSet: true}
}

func (v NullableOutboundIpsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutboundIpsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


