/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the UpdateNotificationPreferences type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotificationPreferences{}

// UpdateNotificationPreferences struct for UpdateNotificationPreferences
type UpdateNotificationPreferences struct {
	EmailOnFailure *bool `json:"email_on_failure,omitempty"`
	EmailOnDeadLetter *bool `json:"email_on_dead_letter,omitempty"`
	EmailOnSuccess *bool `json:"email_on_success,omitempty"`
	SlackWebhookUrl NullableString `json:"slack_webhook_url,omitempty"`
	DiscordWebhookUrl NullableString `json:"discord_webhook_url,omitempty"`
	WebhookUrl NullableString `json:"webhook_url,omitempty"`
}

// NewUpdateNotificationPreferences instantiates a new UpdateNotificationPreferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationPreferences() *UpdateNotificationPreferences {
	this := UpdateNotificationPreferences{}
	return &this
}

// NewUpdateNotificationPreferencesWithDefaults instantiates a new UpdateNotificationPreferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationPreferencesWithDefaults() *UpdateNotificationPreferences {
	this := UpdateNotificationPreferences{}
	return &this
}

// GetEmailOnFailure returns the EmailOnFailure field value if set, zero value otherwise.
func (o *UpdateNotificationPreferences) GetEmailOnFailure() bool {
	if o == nil || IsNil(o.EmailOnFailure) {
		var ret bool
		return ret
	}
	return *o.EmailOnFailure
}

// GetEmailOnFailureOk returns a tuple with the EmailOnFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationPreferences) GetEmailOnFailureOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailOnFailure) {
		return nil, false
	}
	return o.EmailOnFailure, true
}

// HasEmailOnFailure returns a boolean if a field has been set.
func (o *UpdateNotificationPreferences) HasEmailOnFailure() bool {
	if o != nil && !IsNil(o.EmailOnFailure) {
		return true
	}

	return false
}

// SetEmailOnFailure gets a reference to the given bool and assigns it to the EmailOnFailure field.
func (o *UpdateNotificationPreferences) SetEmailOnFailure(v bool) {
	o.EmailOnFailure = &v
}

// GetEmailOnDeadLetter returns the EmailOnDeadLetter field value if set, zero value otherwise.
func (o *UpdateNotificationPreferences) GetEmailOnDeadLetter() bool {
	if o == nil || IsNil(o.EmailOnDeadLetter) {
		var ret bool
		return ret
	}
	return *o.EmailOnDeadLetter
}

// GetEmailOnDeadLetterOk returns a tuple with the EmailOnDeadLetter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationPreferences) GetEmailOnDeadLetterOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailOnDeadLetter) {
		return nil, false
	}
	return o.EmailOnDeadLetter, true
}

// HasEmailOnDeadLetter returns a boolean if a field has been set.
func (o *UpdateNotificationPreferences) HasEmailOnDeadLetter() bool {
	if o != nil && !IsNil(o.EmailOnDeadLetter) {
		return true
	}

	return false
}

// SetEmailOnDeadLetter gets a reference to the given bool and assigns it to the EmailOnDeadLetter field.
func (o *UpdateNotificationPreferences) SetEmailOnDeadLetter(v bool) {
	o.EmailOnDeadLetter = &v
}

// GetEmailOnSuccess returns the EmailOnSuccess field value if set, zero value otherwise.
func (o *UpdateNotificationPreferences) GetEmailOnSuccess() bool {
	if o == nil || IsNil(o.EmailOnSuccess) {
		var ret bool
		return ret
	}
	return *o.EmailOnSuccess
}

// GetEmailOnSuccessOk returns a tuple with the EmailOnSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationPreferences) GetEmailOnSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailOnSuccess) {
		return nil, false
	}
	return o.EmailOnSuccess, true
}

// HasEmailOnSuccess returns a boolean if a field has been set.
func (o *UpdateNotificationPreferences) HasEmailOnSuccess() bool {
	if o != nil && !IsNil(o.EmailOnSuccess) {
		return true
	}

	return false
}

// SetEmailOnSuccess gets a reference to the given bool and assigns it to the EmailOnSuccess field.
func (o *UpdateNotificationPreferences) SetEmailOnSuccess(v bool) {
	o.EmailOnSuccess = &v
}

// GetSlackWebhookUrl returns the SlackWebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNotificationPreferences) GetSlackWebhookUrl() string {
	if o == nil || IsNil(o.SlackWebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SlackWebhookUrl.Get()
}

// GetSlackWebhookUrlOk returns a tuple with the SlackWebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNotificationPreferences) GetSlackWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlackWebhookUrl.Get(), o.SlackWebhookUrl.IsSet()
}

// HasSlackWebhookUrl returns a boolean if a field has been set.
func (o *UpdateNotificationPreferences) HasSlackWebhookUrl() bool {
	if o != nil && o.SlackWebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetSlackWebhookUrl gets a reference to the given NullableString and assigns it to the SlackWebhookUrl field.
func (o *UpdateNotificationPreferences) SetSlackWebhookUrl(v string) {
	o.SlackWebhookUrl.Set(&v)
}
// SetSlackWebhookUrlNil sets the value for SlackWebhookUrl to be an explicit nil
func (o *UpdateNotificationPreferences) SetSlackWebhookUrlNil() {
	o.SlackWebhookUrl.Set(nil)
}

// UnsetSlackWebhookUrl ensures that no value is present for SlackWebhookUrl, not even an explicit nil
func (o *UpdateNotificationPreferences) UnsetSlackWebhookUrl() {
	o.SlackWebhookUrl.Unset()
}

// GetDiscordWebhookUrl returns the DiscordWebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNotificationPreferences) GetDiscordWebhookUrl() string {
	if o == nil || IsNil(o.DiscordWebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DiscordWebhookUrl.Get()
}

// GetDiscordWebhookUrlOk returns a tuple with the DiscordWebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNotificationPreferences) GetDiscordWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscordWebhookUrl.Get(), o.DiscordWebhookUrl.IsSet()
}

// HasDiscordWebhookUrl returns a boolean if a field has been set.
func (o *UpdateNotificationPreferences) HasDiscordWebhookUrl() bool {
	if o != nil && o.DiscordWebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetDiscordWebhookUrl gets a reference to the given NullableString and assigns it to the DiscordWebhookUrl field.
func (o *UpdateNotificationPreferences) SetDiscordWebhookUrl(v string) {
	o.DiscordWebhookUrl.Set(&v)
}
// SetDiscordWebhookUrlNil sets the value for DiscordWebhookUrl to be an explicit nil
func (o *UpdateNotificationPreferences) SetDiscordWebhookUrlNil() {
	o.DiscordWebhookUrl.Set(nil)
}

// UnsetDiscordWebhookUrl ensures that no value is present for DiscordWebhookUrl, not even an explicit nil
func (o *UpdateNotificationPreferences) UnsetDiscordWebhookUrl() {
	o.DiscordWebhookUrl.Unset()
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNotificationPreferences) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookUrl.Get()
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNotificationPreferences) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookUrl.Get(), o.WebhookUrl.IsSet()
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *UpdateNotificationPreferences) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given NullableString and assigns it to the WebhookUrl field.
func (o *UpdateNotificationPreferences) SetWebhookUrl(v string) {
	o.WebhookUrl.Set(&v)
}
// SetWebhookUrlNil sets the value for WebhookUrl to be an explicit nil
func (o *UpdateNotificationPreferences) SetWebhookUrlNil() {
	o.WebhookUrl.Set(nil)
}

// UnsetWebhookUrl ensures that no value is present for WebhookUrl, not even an explicit nil
func (o *UpdateNotificationPreferences) UnsetWebhookUrl() {
	o.WebhookUrl.Unset()
}

func (o UpdateNotificationPreferences) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotificationPreferences) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmailOnFailure) {
		toSerialize["email_on_failure"] = o.EmailOnFailure
	}
	if !IsNil(o.EmailOnDeadLetter) {
		toSerialize["email_on_dead_letter"] = o.EmailOnDeadLetter
	}
	if !IsNil(o.EmailOnSuccess) {
		toSerialize["email_on_success"] = o.EmailOnSuccess
	}
	if o.SlackWebhookUrl.IsSet() {
		toSerialize["slack_webhook_url"] = o.SlackWebhookUrl.Get()
	}
	if o.DiscordWebhookUrl.IsSet() {
		toSerialize["discord_webhook_url"] = o.DiscordWebhookUrl.Get()
	}
	if o.WebhookUrl.IsSet() {
		toSerialize["webhook_url"] = o.WebhookUrl.Get()
	}
	return toSerialize, nil
}

type NullableUpdateNotificationPreferences struct {
	value *UpdateNotificationPreferences
	isSet bool
}

func (v NullableUpdateNotificationPreferences) Get() *UpdateNotificationPreferences {
	return v.value
}

func (v *NullableUpdateNotificationPreferences) Set(val *UpdateNotificationPreferences) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationPreferences) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationPreferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationPreferences(val *UpdateNotificationPreferences) *NullableUpdateNotificationPreferences {
	return &NullableUpdateNotificationPreferences{value: val, isSet: true}
}

func (v NullableUpdateNotificationPreferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationPreferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


