/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
)

// checks if the EndpointHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointHealth{}

// EndpointHealth struct for EndpointHealth
type EndpointHealth struct {
	EndpointId *string `json:"endpoint_id,omitempty"`
	IsHealthy *bool `json:"is_healthy,omitempty"`
	FailureStreak *int32 `json:"failure_streak,omitempty"`
	AvgResponseMs *int32 `json:"avg_response_ms,omitempty"`
	LastFailureAt *time.Time `json:"last_failure_at,omitempty"`
}

// NewEndpointHealth instantiates a new EndpointHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointHealth() *EndpointHealth {
	this := EndpointHealth{}
	return &this
}

// NewEndpointHealthWithDefaults instantiates a new EndpointHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointHealthWithDefaults() *EndpointHealth {
	this := EndpointHealth{}
	return &this
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *EndpointHealth) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointHealth) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *EndpointHealth) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *EndpointHealth) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetIsHealthy returns the IsHealthy field value if set, zero value otherwise.
func (o *EndpointHealth) GetIsHealthy() bool {
	if o == nil || IsNil(o.IsHealthy) {
		var ret bool
		return ret
	}
	return *o.IsHealthy
}

// GetIsHealthyOk returns a tuple with the IsHealthy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointHealth) GetIsHealthyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHealthy) {
		return nil, false
	}
	return o.IsHealthy, true
}

// HasIsHealthy returns a boolean if a field has been set.
func (o *EndpointHealth) HasIsHealthy() bool {
	if o != nil && !IsNil(o.IsHealthy) {
		return true
	}

	return false
}

// SetIsHealthy gets a reference to the given bool and assigns it to the IsHealthy field.
func (o *EndpointHealth) SetIsHealthy(v bool) {
	o.IsHealthy = &v
}

// GetFailureStreak returns the FailureStreak field value if set, zero value otherwise.
func (o *EndpointHealth) GetFailureStreak() int32 {
	if o == nil || IsNil(o.FailureStreak) {
		var ret int32
		return ret
	}
	return *o.FailureStreak
}

// GetFailureStreakOk returns a tuple with the FailureStreak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointHealth) GetFailureStreakOk() (*int32, bool) {
	if o == nil || IsNil(o.FailureStreak) {
		return nil, false
	}
	return o.FailureStreak, true
}

// HasFailureStreak returns a boolean if a field has been set.
func (o *EndpointHealth) HasFailureStreak() bool {
	if o != nil && !IsNil(o.FailureStreak) {
		return true
	}

	return false
}

// SetFailureStreak gets a reference to the given int32 and assigns it to the FailureStreak field.
func (o *EndpointHealth) SetFailureStreak(v int32) {
	o.FailureStreak = &v
}

// GetAvgResponseMs returns the AvgResponseMs field value if set, zero value otherwise.
func (o *EndpointHealth) GetAvgResponseMs() int32 {
	if o == nil || IsNil(o.AvgResponseMs) {
		var ret int32
		return ret
	}
	return *o.AvgResponseMs
}

// GetAvgResponseMsOk returns a tuple with the AvgResponseMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointHealth) GetAvgResponseMsOk() (*int32, bool) {
	if o == nil || IsNil(o.AvgResponseMs) {
		return nil, false
	}
	return o.AvgResponseMs, true
}

// HasAvgResponseMs returns a boolean if a field has been set.
func (o *EndpointHealth) HasAvgResponseMs() bool {
	if o != nil && !IsNil(o.AvgResponseMs) {
		return true
	}

	return false
}

// SetAvgResponseMs gets a reference to the given int32 and assigns it to the AvgResponseMs field.
func (o *EndpointHealth) SetAvgResponseMs(v int32) {
	o.AvgResponseMs = &v
}

// GetLastFailureAt returns the LastFailureAt field value if set, zero value otherwise.
func (o *EndpointHealth) GetLastFailureAt() time.Time {
	if o == nil || IsNil(o.LastFailureAt) {
		var ret time.Time
		return ret
	}
	return *o.LastFailureAt
}

// GetLastFailureAtOk returns a tuple with the LastFailureAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointHealth) GetLastFailureAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastFailureAt) {
		return nil, false
	}
	return o.LastFailureAt, true
}

// HasLastFailureAt returns a boolean if a field has been set.
func (o *EndpointHealth) HasLastFailureAt() bool {
	if o != nil && !IsNil(o.LastFailureAt) {
		return true
	}

	return false
}

// SetLastFailureAt gets a reference to the given time.Time and assigns it to the LastFailureAt field.
func (o *EndpointHealth) SetLastFailureAt(v time.Time) {
	o.LastFailureAt = &v
}

func (o EndpointHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointId) {
		toSerialize["endpoint_id"] = o.EndpointId
	}
	if !IsNil(o.IsHealthy) {
		toSerialize["is_healthy"] = o.IsHealthy
	}
	if !IsNil(o.FailureStreak) {
		toSerialize["failure_streak"] = o.FailureStreak
	}
	if !IsNil(o.AvgResponseMs) {
		toSerialize["avg_response_ms"] = o.AvgResponseMs
	}
	if !IsNil(o.LastFailureAt) {
		toSerialize["last_failure_at"] = o.LastFailureAt
	}
	return toSerialize, nil
}

type NullableEndpointHealth struct {
	value *EndpointHealth
	isSet bool
}

func (v NullableEndpointHealth) Get() *EndpointHealth {
	return v.value
}

func (v *NullableEndpointHealth) Set(val *EndpointHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointHealth(val *EndpointHealth) *NullableEndpointHealth {
	return &NullableEndpointHealth{value: val, isSet: true}
}

func (v NullableEndpointHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


