/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the BatchResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchResponseErrorsInner{}

// BatchResponseErrorsInner struct for BatchResponseErrorsInner
type BatchResponseErrorsInner struct {
	Index *int32 `json:"index,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewBatchResponseErrorsInner instantiates a new BatchResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchResponseErrorsInner() *BatchResponseErrorsInner {
	this := BatchResponseErrorsInner{}
	return &this
}

// NewBatchResponseErrorsInnerWithDefaults instantiates a new BatchResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchResponseErrorsInnerWithDefaults() *BatchResponseErrorsInner {
	this := BatchResponseErrorsInner{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *BatchResponseErrorsInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponseErrorsInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *BatchResponseErrorsInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *BatchResponseErrorsInner) SetIndex(v int32) {
	o.Index = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BatchResponseErrorsInner) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponseErrorsInner) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BatchResponseErrorsInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *BatchResponseErrorsInner) SetError(v string) {
	o.Error = &v
}

func (o BatchResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableBatchResponseErrorsInner struct {
	value *BatchResponseErrorsInner
	isSet bool
}

func (v NullableBatchResponseErrorsInner) Get() *BatchResponseErrorsInner {
	return v.value
}

func (v *NullableBatchResponseErrorsInner) Set(val *BatchResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchResponseErrorsInner(val *BatchResponseErrorsInner) *NullableBatchResponseErrorsInner {
	return &NullableBatchResponseErrorsInner{value: val, isSet: true}
}

func (v NullableBatchResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


