/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the PortalNotificationsPut200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortalNotificationsPut200Response{}

// PortalNotificationsPut200Response struct for PortalNotificationsPut200Response
type PortalNotificationsPut200Response struct {
	Updated *bool `json:"updated,omitempty"`
	Preferences *NotificationPreferences `json:"preferences,omitempty"`
}

// NewPortalNotificationsPut200Response instantiates a new PortalNotificationsPut200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortalNotificationsPut200Response() *PortalNotificationsPut200Response {
	this := PortalNotificationsPut200Response{}
	return &this
}

// NewPortalNotificationsPut200ResponseWithDefaults instantiates a new PortalNotificationsPut200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortalNotificationsPut200ResponseWithDefaults() *PortalNotificationsPut200Response {
	this := PortalNotificationsPut200Response{}
	return &this
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *PortalNotificationsPut200Response) GetUpdated() bool {
	if o == nil || IsNil(o.Updated) {
		var ret bool
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortalNotificationsPut200Response) GetUpdatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *PortalNotificationsPut200Response) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given bool and assigns it to the Updated field.
func (o *PortalNotificationsPut200Response) SetUpdated(v bool) {
	o.Updated = &v
}

// GetPreferences returns the Preferences field value if set, zero value otherwise.
func (o *PortalNotificationsPut200Response) GetPreferences() NotificationPreferences {
	if o == nil || IsNil(o.Preferences) {
		var ret NotificationPreferences
		return ret
	}
	return *o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortalNotificationsPut200Response) GetPreferencesOk() (*NotificationPreferences, bool) {
	if o == nil || IsNil(o.Preferences) {
		return nil, false
	}
	return o.Preferences, true
}

// HasPreferences returns a boolean if a field has been set.
func (o *PortalNotificationsPut200Response) HasPreferences() bool {
	if o != nil && !IsNil(o.Preferences) {
		return true
	}

	return false
}

// SetPreferences gets a reference to the given NotificationPreferences and assigns it to the Preferences field.
func (o *PortalNotificationsPut200Response) SetPreferences(v NotificationPreferences) {
	o.Preferences = &v
}

func (o PortalNotificationsPut200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortalNotificationsPut200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Preferences) {
		toSerialize["preferences"] = o.Preferences
	}
	return toSerialize, nil
}

type NullablePortalNotificationsPut200Response struct {
	value *PortalNotificationsPut200Response
	isSet bool
}

func (v NullablePortalNotificationsPut200Response) Get() *PortalNotificationsPut200Response {
	return v.value
}

func (v *NullablePortalNotificationsPut200Response) Set(val *PortalNotificationsPut200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePortalNotificationsPut200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePortalNotificationsPut200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortalNotificationsPut200Response(val *PortalNotificationsPut200Response) *NullablePortalNotificationsPut200Response {
	return &NullablePortalNotificationsPut200Response{value: val, isSet: true}
}

func (v NullablePortalNotificationsPut200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortalNotificationsPut200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


