/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchReplayRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchReplayRequest{}

// BatchReplayRequest struct for BatchReplayRequest
type BatchReplayRequest struct {
	Ids []string `json:"ids"`
}

type _BatchReplayRequest BatchReplayRequest

// NewBatchReplayRequest instantiates a new BatchReplayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchReplayRequest(ids []string) *BatchReplayRequest {
	this := BatchReplayRequest{}
	this.Ids = ids
	return &this
}

// NewBatchReplayRequestWithDefaults instantiates a new BatchReplayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchReplayRequestWithDefaults() *BatchReplayRequest {
	this := BatchReplayRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *BatchReplayRequest) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *BatchReplayRequest) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *BatchReplayRequest) SetIds(v []string) {
	o.Ids = v
}

func (o BatchReplayRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchReplayRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *BatchReplayRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchReplayRequest := _BatchReplayRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchReplayRequest)

	if err != nil {
		return err
	}

	*o = BatchReplayRequest(varBatchReplayRequest)

	return err
}

type NullableBatchReplayRequest struct {
	value *BatchReplayRequest
	isSet bool
}

func (v NullableBatchReplayRequest) Get() *BatchReplayRequest {
	return v.value
}

func (v *NullableBatchReplayRequest) Set(val *BatchReplayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchReplayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchReplayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchReplayRequest(val *BatchReplayRequest) *NullableBatchReplayRequest {
	return &NullableBatchReplayRequest{value: val, isSet: true}
}

func (v NullableBatchReplayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchReplayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


