/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AuthLoginPost200Response - struct for AuthLoginPost200Response
type AuthLoginPost200Response struct {
	AuthResponse *AuthResponse
	TwoFactorRequiredResponse *TwoFactorRequiredResponse
}

// AuthResponseAsAuthLoginPost200Response is a convenience function that returns AuthResponse wrapped in AuthLoginPost200Response
func AuthResponseAsAuthLoginPost200Response(v *AuthResponse) AuthLoginPost200Response {
	return AuthLoginPost200Response{
		AuthResponse: v,
	}
}

// TwoFactorRequiredResponseAsAuthLoginPost200Response is a convenience function that returns TwoFactorRequiredResponse wrapped in AuthLoginPost200Response
func TwoFactorRequiredResponseAsAuthLoginPost200Response(v *TwoFactorRequiredResponse) AuthLoginPost200Response {
	return AuthLoginPost200Response{
		TwoFactorRequiredResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AuthLoginPost200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AuthResponse
	err = newStrictDecoder(data).Decode(&dst.AuthResponse)
	if err == nil {
		jsonAuthResponse, _ := json.Marshal(dst.AuthResponse)
		if string(jsonAuthResponse) == "{}" { // empty struct
			dst.AuthResponse = nil
		} else {
			if err = validator.Validate(dst.AuthResponse); err != nil {
				dst.AuthResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthResponse = nil
	}

	// try to unmarshal data into TwoFactorRequiredResponse
	err = newStrictDecoder(data).Decode(&dst.TwoFactorRequiredResponse)
	if err == nil {
		jsonTwoFactorRequiredResponse, _ := json.Marshal(dst.TwoFactorRequiredResponse)
		if string(jsonTwoFactorRequiredResponse) == "{}" { // empty struct
			dst.TwoFactorRequiredResponse = nil
		} else {
			if err = validator.Validate(dst.TwoFactorRequiredResponse); err != nil {
				dst.TwoFactorRequiredResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.TwoFactorRequiredResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AuthResponse = nil
		dst.TwoFactorRequiredResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AuthLoginPost200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AuthLoginPost200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AuthLoginPost200Response) MarshalJSON() ([]byte, error) {
	if src.AuthResponse != nil {
		return json.Marshal(&src.AuthResponse)
	}

	if src.TwoFactorRequiredResponse != nil {
		return json.Marshal(&src.TwoFactorRequiredResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AuthLoginPost200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AuthResponse != nil {
		return obj.AuthResponse
	}

	if obj.TwoFactorRequiredResponse != nil {
		return obj.TwoFactorRequiredResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AuthLoginPost200Response) GetActualInstanceValue() (interface{}) {
	if obj.AuthResponse != nil {
		return *obj.AuthResponse
	}

	if obj.TwoFactorRequiredResponse != nil {
		return *obj.TwoFactorRequiredResponse
	}

	// all schemas are nil
	return nil
}

type NullableAuthLoginPost200Response struct {
	value *AuthLoginPost200Response
	isSet bool
}

func (v NullableAuthLoginPost200Response) Get() *AuthLoginPost200Response {
	return v.value
}

func (v *NullableAuthLoginPost200Response) Set(val *AuthLoginPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLoginPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLoginPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLoginPost200Response(val *AuthLoginPost200Response) *NullableAuthLoginPost200Response {
	return &NullableAuthLoginPost200Response{value: val, isSet: true}
}

func (v NullableAuthLoginPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLoginPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


