/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the RoutingInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingInfo{}

// RoutingInfo struct for RoutingInfo
type RoutingInfo struct {
	EndpointId *string `json:"endpoint_id,omitempty"`
	RoutingStrategy *string `json:"routing_strategy,omitempty"`
	FallbackUrl NullableString `json:"fallback_url,omitempty"`
	AvgResponseMs *int32 `json:"avg_response_ms,omitempty"`
	FailureStreak *int32 `json:"failure_streak,omitempty"`
	IsHealthy *bool `json:"is_healthy,omitempty"`
}

// NewRoutingInfo instantiates a new RoutingInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingInfo() *RoutingInfo {
	this := RoutingInfo{}
	return &this
}

// NewRoutingInfoWithDefaults instantiates a new RoutingInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingInfoWithDefaults() *RoutingInfo {
	this := RoutingInfo{}
	return &this
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *RoutingInfo) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingInfo) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *RoutingInfo) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *RoutingInfo) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetRoutingStrategy returns the RoutingStrategy field value if set, zero value otherwise.
func (o *RoutingInfo) GetRoutingStrategy() string {
	if o == nil || IsNil(o.RoutingStrategy) {
		var ret string
		return ret
	}
	return *o.RoutingStrategy
}

// GetRoutingStrategyOk returns a tuple with the RoutingStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingInfo) GetRoutingStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingStrategy) {
		return nil, false
	}
	return o.RoutingStrategy, true
}

// HasRoutingStrategy returns a boolean if a field has been set.
func (o *RoutingInfo) HasRoutingStrategy() bool {
	if o != nil && !IsNil(o.RoutingStrategy) {
		return true
	}

	return false
}

// SetRoutingStrategy gets a reference to the given string and assigns it to the RoutingStrategy field.
func (o *RoutingInfo) SetRoutingStrategy(v string) {
	o.RoutingStrategy = &v
}

// GetFallbackUrl returns the FallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoutingInfo) GetFallbackUrl() string {
	if o == nil || IsNil(o.FallbackUrl.Get()) {
		var ret string
		return ret
	}
	return *o.FallbackUrl.Get()
}

// GetFallbackUrlOk returns a tuple with the FallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoutingInfo) GetFallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FallbackUrl.Get(), o.FallbackUrl.IsSet()
}

// HasFallbackUrl returns a boolean if a field has been set.
func (o *RoutingInfo) HasFallbackUrl() bool {
	if o != nil && o.FallbackUrl.IsSet() {
		return true
	}

	return false
}

// SetFallbackUrl gets a reference to the given NullableString and assigns it to the FallbackUrl field.
func (o *RoutingInfo) SetFallbackUrl(v string) {
	o.FallbackUrl.Set(&v)
}
// SetFallbackUrlNil sets the value for FallbackUrl to be an explicit nil
func (o *RoutingInfo) SetFallbackUrlNil() {
	o.FallbackUrl.Set(nil)
}

// UnsetFallbackUrl ensures that no value is present for FallbackUrl, not even an explicit nil
func (o *RoutingInfo) UnsetFallbackUrl() {
	o.FallbackUrl.Unset()
}

// GetAvgResponseMs returns the AvgResponseMs field value if set, zero value otherwise.
func (o *RoutingInfo) GetAvgResponseMs() int32 {
	if o == nil || IsNil(o.AvgResponseMs) {
		var ret int32
		return ret
	}
	return *o.AvgResponseMs
}

// GetAvgResponseMsOk returns a tuple with the AvgResponseMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingInfo) GetAvgResponseMsOk() (*int32, bool) {
	if o == nil || IsNil(o.AvgResponseMs) {
		return nil, false
	}
	return o.AvgResponseMs, true
}

// HasAvgResponseMs returns a boolean if a field has been set.
func (o *RoutingInfo) HasAvgResponseMs() bool {
	if o != nil && !IsNil(o.AvgResponseMs) {
		return true
	}

	return false
}

// SetAvgResponseMs gets a reference to the given int32 and assigns it to the AvgResponseMs field.
func (o *RoutingInfo) SetAvgResponseMs(v int32) {
	o.AvgResponseMs = &v
}

// GetFailureStreak returns the FailureStreak field value if set, zero value otherwise.
func (o *RoutingInfo) GetFailureStreak() int32 {
	if o == nil || IsNil(o.FailureStreak) {
		var ret int32
		return ret
	}
	return *o.FailureStreak
}

// GetFailureStreakOk returns a tuple with the FailureStreak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingInfo) GetFailureStreakOk() (*int32, bool) {
	if o == nil || IsNil(o.FailureStreak) {
		return nil, false
	}
	return o.FailureStreak, true
}

// HasFailureStreak returns a boolean if a field has been set.
func (o *RoutingInfo) HasFailureStreak() bool {
	if o != nil && !IsNil(o.FailureStreak) {
		return true
	}

	return false
}

// SetFailureStreak gets a reference to the given int32 and assigns it to the FailureStreak field.
func (o *RoutingInfo) SetFailureStreak(v int32) {
	o.FailureStreak = &v
}

// GetIsHealthy returns the IsHealthy field value if set, zero value otherwise.
func (o *RoutingInfo) GetIsHealthy() bool {
	if o == nil || IsNil(o.IsHealthy) {
		var ret bool
		return ret
	}
	return *o.IsHealthy
}

// GetIsHealthyOk returns a tuple with the IsHealthy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingInfo) GetIsHealthyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHealthy) {
		return nil, false
	}
	return o.IsHealthy, true
}

// HasIsHealthy returns a boolean if a field has been set.
func (o *RoutingInfo) HasIsHealthy() bool {
	if o != nil && !IsNil(o.IsHealthy) {
		return true
	}

	return false
}

// SetIsHealthy gets a reference to the given bool and assigns it to the IsHealthy field.
func (o *RoutingInfo) SetIsHealthy(v bool) {
	o.IsHealthy = &v
}

func (o RoutingInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointId) {
		toSerialize["endpoint_id"] = o.EndpointId
	}
	if !IsNil(o.RoutingStrategy) {
		toSerialize["routing_strategy"] = o.RoutingStrategy
	}
	if o.FallbackUrl.IsSet() {
		toSerialize["fallback_url"] = o.FallbackUrl.Get()
	}
	if !IsNil(o.AvgResponseMs) {
		toSerialize["avg_response_ms"] = o.AvgResponseMs
	}
	if !IsNil(o.FailureStreak) {
		toSerialize["failure_streak"] = o.FailureStreak
	}
	if !IsNil(o.IsHealthy) {
		toSerialize["is_healthy"] = o.IsHealthy
	}
	return toSerialize, nil
}

type NullableRoutingInfo struct {
	value *RoutingInfo
	isSet bool
}

func (v NullableRoutingInfo) Get() *RoutingInfo {
	return v.value
}

func (v *NullableRoutingInfo) Set(val *RoutingInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingInfo(val *RoutingInfo) *NullableRoutingInfo {
	return &NullableRoutingInfo{value: val, isSet: true}
}

func (v NullableRoutingInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


