/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the ApplyTemplateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyTemplateResponse{}

// ApplyTemplateResponse struct for ApplyTemplateResponse
type ApplyTemplateResponse struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewApplyTemplateResponse instantiates a new ApplyTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyTemplateResponse() *ApplyTemplateResponse {
	this := ApplyTemplateResponse{}
	return &this
}

// NewApplyTemplateResponseWithDefaults instantiates a new ApplyTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyTemplateResponseWithDefaults() *ApplyTemplateResponse {
	this := ApplyTemplateResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApplyTemplateResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTemplateResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApplyTemplateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApplyTemplateResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApplyTemplateResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTemplateResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApplyTemplateResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApplyTemplateResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ApplyTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyTemplateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableApplyTemplateResponse struct {
	value *ApplyTemplateResponse
	isSet bool
}

func (v NullableApplyTemplateResponse) Get() *ApplyTemplateResponse {
	return v.value
}

func (v *NullableApplyTemplateResponse) Set(val *ApplyTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyTemplateResponse(val *ApplyTemplateResponse) *NullableApplyTemplateResponse {
	return &NullableApplyTemplateResponse{value: val, isSet: true}
}

func (v NullableApplyTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


