/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the UpdateRoutingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRoutingRequest{}

// UpdateRoutingRequest struct for UpdateRoutingRequest
type UpdateRoutingRequest struct {
	RoutingStrategy *string `json:"routing_strategy,omitempty"`
	FallbackUrl *string `json:"fallback_url,omitempty"`
}

// NewUpdateRoutingRequest instantiates a new UpdateRoutingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRoutingRequest() *UpdateRoutingRequest {
	this := UpdateRoutingRequest{}
	return &this
}

// NewUpdateRoutingRequestWithDefaults instantiates a new UpdateRoutingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRoutingRequestWithDefaults() *UpdateRoutingRequest {
	this := UpdateRoutingRequest{}
	return &this
}

// GetRoutingStrategy returns the RoutingStrategy field value if set, zero value otherwise.
func (o *UpdateRoutingRequest) GetRoutingStrategy() string {
	if o == nil || IsNil(o.RoutingStrategy) {
		var ret string
		return ret
	}
	return *o.RoutingStrategy
}

// GetRoutingStrategyOk returns a tuple with the RoutingStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRoutingRequest) GetRoutingStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingStrategy) {
		return nil, false
	}
	return o.RoutingStrategy, true
}

// HasRoutingStrategy returns a boolean if a field has been set.
func (o *UpdateRoutingRequest) HasRoutingStrategy() bool {
	if o != nil && !IsNil(o.RoutingStrategy) {
		return true
	}

	return false
}

// SetRoutingStrategy gets a reference to the given string and assigns it to the RoutingStrategy field.
func (o *UpdateRoutingRequest) SetRoutingStrategy(v string) {
	o.RoutingStrategy = &v
}

// GetFallbackUrl returns the FallbackUrl field value if set, zero value otherwise.
func (o *UpdateRoutingRequest) GetFallbackUrl() string {
	if o == nil || IsNil(o.FallbackUrl) {
		var ret string
		return ret
	}
	return *o.FallbackUrl
}

// GetFallbackUrlOk returns a tuple with the FallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRoutingRequest) GetFallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FallbackUrl) {
		return nil, false
	}
	return o.FallbackUrl, true
}

// HasFallbackUrl returns a boolean if a field has been set.
func (o *UpdateRoutingRequest) HasFallbackUrl() bool {
	if o != nil && !IsNil(o.FallbackUrl) {
		return true
	}

	return false
}

// SetFallbackUrl gets a reference to the given string and assigns it to the FallbackUrl field.
func (o *UpdateRoutingRequest) SetFallbackUrl(v string) {
	o.FallbackUrl = &v
}

func (o UpdateRoutingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRoutingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoutingStrategy) {
		toSerialize["routing_strategy"] = o.RoutingStrategy
	}
	if !IsNil(o.FallbackUrl) {
		toSerialize["fallback_url"] = o.FallbackUrl
	}
	return toSerialize, nil
}

type NullableUpdateRoutingRequest struct {
	value *UpdateRoutingRequest
	isSet bool
}

func (v NullableUpdateRoutingRequest) Get() *UpdateRoutingRequest {
	return v.value
}

func (v *NullableUpdateRoutingRequest) Set(val *UpdateRoutingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRoutingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRoutingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRoutingRequest(val *UpdateRoutingRequest) *NullableUpdateRoutingRequest {
	return &NullableUpdateRoutingRequest{value: val, isSet: true}
}

func (v NullableUpdateRoutingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRoutingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


