/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the AdminRevenueGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminRevenueGet200ResponseInner{}

// AdminRevenueGet200ResponseInner struct for AdminRevenueGet200ResponseInner
type AdminRevenueGet200ResponseInner struct {
	Month *string `json:"month,omitempty"`
	RevenueCents *int32 `json:"revenue_cents,omitempty"`
	SubscriberCount *int32 `json:"subscriber_count,omitempty"`
}

// NewAdminRevenueGet200ResponseInner instantiates a new AdminRevenueGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminRevenueGet200ResponseInner() *AdminRevenueGet200ResponseInner {
	this := AdminRevenueGet200ResponseInner{}
	return &this
}

// NewAdminRevenueGet200ResponseInnerWithDefaults instantiates a new AdminRevenueGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminRevenueGet200ResponseInnerWithDefaults() *AdminRevenueGet200ResponseInner {
	this := AdminRevenueGet200ResponseInner{}
	return &this
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *AdminRevenueGet200ResponseInner) GetMonth() string {
	if o == nil || IsNil(o.Month) {
		var ret string
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminRevenueGet200ResponseInner) GetMonthOk() (*string, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *AdminRevenueGet200ResponseInner) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given string and assigns it to the Month field.
func (o *AdminRevenueGet200ResponseInner) SetMonth(v string) {
	o.Month = &v
}

// GetRevenueCents returns the RevenueCents field value if set, zero value otherwise.
func (o *AdminRevenueGet200ResponseInner) GetRevenueCents() int32 {
	if o == nil || IsNil(o.RevenueCents) {
		var ret int32
		return ret
	}
	return *o.RevenueCents
}

// GetRevenueCentsOk returns a tuple with the RevenueCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminRevenueGet200ResponseInner) GetRevenueCentsOk() (*int32, bool) {
	if o == nil || IsNil(o.RevenueCents) {
		return nil, false
	}
	return o.RevenueCents, true
}

// HasRevenueCents returns a boolean if a field has been set.
func (o *AdminRevenueGet200ResponseInner) HasRevenueCents() bool {
	if o != nil && !IsNil(o.RevenueCents) {
		return true
	}

	return false
}

// SetRevenueCents gets a reference to the given int32 and assigns it to the RevenueCents field.
func (o *AdminRevenueGet200ResponseInner) SetRevenueCents(v int32) {
	o.RevenueCents = &v
}

// GetSubscriberCount returns the SubscriberCount field value if set, zero value otherwise.
func (o *AdminRevenueGet200ResponseInner) GetSubscriberCount() int32 {
	if o == nil || IsNil(o.SubscriberCount) {
		var ret int32
		return ret
	}
	return *o.SubscriberCount
}

// GetSubscriberCountOk returns a tuple with the SubscriberCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminRevenueGet200ResponseInner) GetSubscriberCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SubscriberCount) {
		return nil, false
	}
	return o.SubscriberCount, true
}

// HasSubscriberCount returns a boolean if a field has been set.
func (o *AdminRevenueGet200ResponseInner) HasSubscriberCount() bool {
	if o != nil && !IsNil(o.SubscriberCount) {
		return true
	}

	return false
}

// SetSubscriberCount gets a reference to the given int32 and assigns it to the SubscriberCount field.
func (o *AdminRevenueGet200ResponseInner) SetSubscriberCount(v int32) {
	o.SubscriberCount = &v
}

func (o AdminRevenueGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminRevenueGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.RevenueCents) {
		toSerialize["revenue_cents"] = o.RevenueCents
	}
	if !IsNil(o.SubscriberCount) {
		toSerialize["subscriber_count"] = o.SubscriberCount
	}
	return toSerialize, nil
}

type NullableAdminRevenueGet200ResponseInner struct {
	value *AdminRevenueGet200ResponseInner
	isSet bool
}

func (v NullableAdminRevenueGet200ResponseInner) Get() *AdminRevenueGet200ResponseInner {
	return v.value
}

func (v *NullableAdminRevenueGet200ResponseInner) Set(val *AdminRevenueGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminRevenueGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminRevenueGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminRevenueGet200ResponseInner(val *AdminRevenueGet200ResponseInner) *NullableAdminRevenueGet200ResponseInner {
	return &NullableAdminRevenueGet200ResponseInner{value: val, isSet: true}
}

func (v NullableAdminRevenueGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminRevenueGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


