/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the DeliveryListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryListResponse{}

// DeliveryListResponse struct for DeliveryListResponse
type DeliveryListResponse struct {
	Deliveries []Delivery `json:"deliveries,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Page *int32 `json:"page,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
}

// NewDeliveryListResponse instantiates a new DeliveryListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryListResponse() *DeliveryListResponse {
	this := DeliveryListResponse{}
	return &this
}

// NewDeliveryListResponseWithDefaults instantiates a new DeliveryListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryListResponseWithDefaults() *DeliveryListResponse {
	this := DeliveryListResponse{}
	return &this
}

// GetDeliveries returns the Deliveries field value if set, zero value otherwise.
func (o *DeliveryListResponse) GetDeliveries() []Delivery {
	if o == nil || IsNil(o.Deliveries) {
		var ret []Delivery
		return ret
	}
	return o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryListResponse) GetDeliveriesOk() ([]Delivery, bool) {
	if o == nil || IsNil(o.Deliveries) {
		return nil, false
	}
	return o.Deliveries, true
}

// HasDeliveries returns a boolean if a field has been set.
func (o *DeliveryListResponse) HasDeliveries() bool {
	if o != nil && !IsNil(o.Deliveries) {
		return true
	}

	return false
}

// SetDeliveries gets a reference to the given []Delivery and assigns it to the Deliveries field.
func (o *DeliveryListResponse) SetDeliveries(v []Delivery) {
	o.Deliveries = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *DeliveryListResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryListResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *DeliveryListResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *DeliveryListResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *DeliveryListResponse) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryListResponse) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *DeliveryListResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *DeliveryListResponse) SetPage(v int32) {
	o.Page = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *DeliveryListResponse) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryListResponse) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *DeliveryListResponse) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *DeliveryListResponse) SetPerPage(v int32) {
	o.PerPage = &v
}

func (o DeliveryListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deliveries) {
		toSerialize["deliveries"] = o.Deliveries
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	return toSerialize, nil
}

type NullableDeliveryListResponse struct {
	value *DeliveryListResponse
	isSet bool
}

func (v NullableDeliveryListResponse) Get() *DeliveryListResponse {
	return v.value
}

func (v *NullableDeliveryListResponse) Set(val *DeliveryListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryListResponse(val *DeliveryListResponse) *NullableDeliveryListResponse {
	return &NullableDeliveryListResponse{value: val, isSet: true}
}

func (v NullableDeliveryListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


