/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTeamRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTeamRequest{}

// CreateTeamRequest struct for CreateTeamRequest
type CreateTeamRequest struct {
	Name string `json:"name"`
}

type _CreateTeamRequest CreateTeamRequest

// NewCreateTeamRequest instantiates a new CreateTeamRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTeamRequest(name string) *CreateTeamRequest {
	this := CreateTeamRequest{}
	this.Name = name
	return &this
}

// NewCreateTeamRequestWithDefaults instantiates a new CreateTeamRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTeamRequestWithDefaults() *CreateTeamRequest {
	this := CreateTeamRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTeamRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTeamRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTeamRequest) SetName(v string) {
	o.Name = v
}

func (o CreateTeamRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTeamRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateTeamRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTeamRequest := _CreateTeamRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTeamRequest)

	if err != nil {
		return err
	}

	*o = CreateTeamRequest(varCreateTeamRequest)

	return err
}

type NullableCreateTeamRequest struct {
	value *CreateTeamRequest
	isSet bool
}

func (v NullableCreateTeamRequest) Get() *CreateTeamRequest {
	return v.value
}

func (v *NullableCreateTeamRequest) Set(val *CreateTeamRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTeamRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTeamRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTeamRequest(val *CreateTeamRequest) *NullableCreateTeamRequest {
	return &NullableCreateTeamRequest{value: val, isSet: true}
}

func (v NullableCreateTeamRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTeamRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


