/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"time"
)

// checks if the UsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageResponse{}

// UsageResponse struct for UsageResponse
type UsageResponse struct {
	Plan *string `json:"plan,omitempty"`
	PeriodStart *time.Time `json:"period_start,omitempty"`
	PeriodEnd *time.Time `json:"period_end,omitempty"`
	WebhooksUsed *int32 `json:"webhooks_used,omitempty"`
	WebhooksLimit *int32 `json:"webhooks_limit,omitempty"`
	EndpointsUsed *int32 `json:"endpoints_used,omitempty"`
	EndpointsLimit *int32 `json:"endpoints_limit,omitempty"`
}

// NewUsageResponse instantiates a new UsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageResponse() *UsageResponse {
	this := UsageResponse{}
	return &this
}

// NewUsageResponseWithDefaults instantiates a new UsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageResponseWithDefaults() *UsageResponse {
	this := UsageResponse{}
	return &this
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *UsageResponse) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *UsageResponse) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *UsageResponse) SetPlan(v string) {
	o.Plan = &v
}

// GetPeriodStart returns the PeriodStart field value if set, zero value otherwise.
func (o *UsageResponse) GetPeriodStart() time.Time {
	if o == nil || IsNil(o.PeriodStart) {
		var ret time.Time
		return ret
	}
	return *o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetPeriodStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PeriodStart) {
		return nil, false
	}
	return o.PeriodStart, true
}

// HasPeriodStart returns a boolean if a field has been set.
func (o *UsageResponse) HasPeriodStart() bool {
	if o != nil && !IsNil(o.PeriodStart) {
		return true
	}

	return false
}

// SetPeriodStart gets a reference to the given time.Time and assigns it to the PeriodStart field.
func (o *UsageResponse) SetPeriodStart(v time.Time) {
	o.PeriodStart = &v
}

// GetPeriodEnd returns the PeriodEnd field value if set, zero value otherwise.
func (o *UsageResponse) GetPeriodEnd() time.Time {
	if o == nil || IsNil(o.PeriodEnd) {
		var ret time.Time
		return ret
	}
	return *o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetPeriodEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PeriodEnd) {
		return nil, false
	}
	return o.PeriodEnd, true
}

// HasPeriodEnd returns a boolean if a field has been set.
func (o *UsageResponse) HasPeriodEnd() bool {
	if o != nil && !IsNil(o.PeriodEnd) {
		return true
	}

	return false
}

// SetPeriodEnd gets a reference to the given time.Time and assigns it to the PeriodEnd field.
func (o *UsageResponse) SetPeriodEnd(v time.Time) {
	o.PeriodEnd = &v
}

// GetWebhooksUsed returns the WebhooksUsed field value if set, zero value otherwise.
func (o *UsageResponse) GetWebhooksUsed() int32 {
	if o == nil || IsNil(o.WebhooksUsed) {
		var ret int32
		return ret
	}
	return *o.WebhooksUsed
}

// GetWebhooksUsedOk returns a tuple with the WebhooksUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetWebhooksUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.WebhooksUsed) {
		return nil, false
	}
	return o.WebhooksUsed, true
}

// HasWebhooksUsed returns a boolean if a field has been set.
func (o *UsageResponse) HasWebhooksUsed() bool {
	if o != nil && !IsNil(o.WebhooksUsed) {
		return true
	}

	return false
}

// SetWebhooksUsed gets a reference to the given int32 and assigns it to the WebhooksUsed field.
func (o *UsageResponse) SetWebhooksUsed(v int32) {
	o.WebhooksUsed = &v
}

// GetWebhooksLimit returns the WebhooksLimit field value if set, zero value otherwise.
func (o *UsageResponse) GetWebhooksLimit() int32 {
	if o == nil || IsNil(o.WebhooksLimit) {
		var ret int32
		return ret
	}
	return *o.WebhooksLimit
}

// GetWebhooksLimitOk returns a tuple with the WebhooksLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetWebhooksLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.WebhooksLimit) {
		return nil, false
	}
	return o.WebhooksLimit, true
}

// HasWebhooksLimit returns a boolean if a field has been set.
func (o *UsageResponse) HasWebhooksLimit() bool {
	if o != nil && !IsNil(o.WebhooksLimit) {
		return true
	}

	return false
}

// SetWebhooksLimit gets a reference to the given int32 and assigns it to the WebhooksLimit field.
func (o *UsageResponse) SetWebhooksLimit(v int32) {
	o.WebhooksLimit = &v
}

// GetEndpointsUsed returns the EndpointsUsed field value if set, zero value otherwise.
func (o *UsageResponse) GetEndpointsUsed() int32 {
	if o == nil || IsNil(o.EndpointsUsed) {
		var ret int32
		return ret
	}
	return *o.EndpointsUsed
}

// GetEndpointsUsedOk returns a tuple with the EndpointsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetEndpointsUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.EndpointsUsed) {
		return nil, false
	}
	return o.EndpointsUsed, true
}

// HasEndpointsUsed returns a boolean if a field has been set.
func (o *UsageResponse) HasEndpointsUsed() bool {
	if o != nil && !IsNil(o.EndpointsUsed) {
		return true
	}

	return false
}

// SetEndpointsUsed gets a reference to the given int32 and assigns it to the EndpointsUsed field.
func (o *UsageResponse) SetEndpointsUsed(v int32) {
	o.EndpointsUsed = &v
}

// GetEndpointsLimit returns the EndpointsLimit field value if set, zero value otherwise.
func (o *UsageResponse) GetEndpointsLimit() int32 {
	if o == nil || IsNil(o.EndpointsLimit) {
		var ret int32
		return ret
	}
	return *o.EndpointsLimit
}

// GetEndpointsLimitOk returns a tuple with the EndpointsLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetEndpointsLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.EndpointsLimit) {
		return nil, false
	}
	return o.EndpointsLimit, true
}

// HasEndpointsLimit returns a boolean if a field has been set.
func (o *UsageResponse) HasEndpointsLimit() bool {
	if o != nil && !IsNil(o.EndpointsLimit) {
		return true
	}

	return false
}

// SetEndpointsLimit gets a reference to the given int32 and assigns it to the EndpointsLimit field.
func (o *UsageResponse) SetEndpointsLimit(v int32) {
	o.EndpointsLimit = &v
}

func (o UsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.PeriodStart) {
		toSerialize["period_start"] = o.PeriodStart
	}
	if !IsNil(o.PeriodEnd) {
		toSerialize["period_end"] = o.PeriodEnd
	}
	if !IsNil(o.WebhooksUsed) {
		toSerialize["webhooks_used"] = o.WebhooksUsed
	}
	if !IsNil(o.WebhooksLimit) {
		toSerialize["webhooks_limit"] = o.WebhooksLimit
	}
	if !IsNil(o.EndpointsUsed) {
		toSerialize["endpoints_used"] = o.EndpointsUsed
	}
	if !IsNil(o.EndpointsLimit) {
		toSerialize["endpoints_limit"] = o.EndpointsLimit
	}
	return toSerialize, nil
}

type NullableUsageResponse struct {
	value *UsageResponse
	isSet bool
}

func (v NullableUsageResponse) Get() *UsageResponse {
	return v.value
}

func (v *NullableUsageResponse) Set(val *UsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageResponse(val *UsageResponse) *NullableUsageResponse {
	return &NullableUsageResponse{value: val, isSet: true}
}

func (v NullableUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


