/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Enable2faRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Enable2faRequest{}

// Enable2faRequest struct for Enable2faRequest
type Enable2faRequest struct {
	Password string `json:"password"`
}

type _Enable2faRequest Enable2faRequest

// NewEnable2faRequest instantiates a new Enable2faRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnable2faRequest(password string) *Enable2faRequest {
	this := Enable2faRequest{}
	this.Password = password
	return &this
}

// NewEnable2faRequestWithDefaults instantiates a new Enable2faRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnable2faRequestWithDefaults() *Enable2faRequest {
	this := Enable2faRequest{}
	return &this
}

// GetPassword returns the Password field value
func (o *Enable2faRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *Enable2faRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *Enable2faRequest) SetPassword(v string) {
	o.Password = v
}

func (o Enable2faRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Enable2faRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *Enable2faRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnable2faRequest := _Enable2faRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnable2faRequest)

	if err != nil {
		return err
	}

	*o = Enable2faRequest(varEnable2faRequest)

	return err
}

type NullableEnable2faRequest struct {
	value *Enable2faRequest
	isSet bool
}

func (v NullableEnable2faRequest) Get() *Enable2faRequest {
	return v.value
}

func (v *NullableEnable2faRequest) Set(val *Enable2faRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnable2faRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnable2faRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnable2faRequest(val *Enable2faRequest) *NullableEnable2faRequest {
	return &NullableEnable2faRequest{value: val, isSet: true}
}

func (v NullableEnable2faRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnable2faRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


