/*
HookSniff API

Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 

API version: 1.0.0
Contact: support@hooksniff.vercel.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hooksniff

import (
	"encoding/json"
)

// checks if the BatchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchResponse{}

// BatchResponse struct for BatchResponse
type BatchResponse struct {
	Deliveries []Delivery `json:"deliveries,omitempty"`
	Errors []BatchResponseErrorsInner `json:"errors,omitempty"`
}

// NewBatchResponse instantiates a new BatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchResponse() *BatchResponse {
	this := BatchResponse{}
	return &this
}

// NewBatchResponseWithDefaults instantiates a new BatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchResponseWithDefaults() *BatchResponse {
	this := BatchResponse{}
	return &this
}

// GetDeliveries returns the Deliveries field value if set, zero value otherwise.
func (o *BatchResponse) GetDeliveries() []Delivery {
	if o == nil || IsNil(o.Deliveries) {
		var ret []Delivery
		return ret
	}
	return o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetDeliveriesOk() ([]Delivery, bool) {
	if o == nil || IsNil(o.Deliveries) {
		return nil, false
	}
	return o.Deliveries, true
}

// HasDeliveries returns a boolean if a field has been set.
func (o *BatchResponse) HasDeliveries() bool {
	if o != nil && !IsNil(o.Deliveries) {
		return true
	}

	return false
}

// SetDeliveries gets a reference to the given []Delivery and assigns it to the Deliveries field.
func (o *BatchResponse) SetDeliveries(v []Delivery) {
	o.Deliveries = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *BatchResponse) GetErrors() []BatchResponseErrorsInner {
	if o == nil || IsNil(o.Errors) {
		var ret []BatchResponseErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetErrorsOk() ([]BatchResponseErrorsInner, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BatchResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []BatchResponseErrorsInner and assigns it to the Errors field.
func (o *BatchResponse) SetErrors(v []BatchResponseErrorsInner) {
	o.Errors = v
}

func (o BatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deliveries) {
		toSerialize["deliveries"] = o.Deliveries
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableBatchResponse struct {
	value *BatchResponse
	isSet bool
}

func (v NullableBatchResponse) Get() *BatchResponse {
	return v.value
}

func (v *NullableBatchResponse) Set(val *BatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchResponse(val *BatchResponse) *NullableBatchResponse {
	return &NullableBatchResponse{value: val, isSet: true}
}

func (v NullableBatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


